### ISSUE TITLE
JOSS review: contribution guidelines

### ISSUE THREAD

**Issue by AlexanderFabisch** [NVlabs/scene_synthesizer#5]
Currently missing:

> Community guidelines: Are there clear guidelines for third parties wishing to 1. Contribute to the software 2. Report issues or problems with the software 3. Seek support

More information: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

https://github.com/openjournals/joss-reviews/issues/7561

**Comment by clemense** [comment]
Thanks! I added a file `CONTRIBUTION.md` and linked it from the README.  (https://github.com/NVlabs/scene_synthesizer/commit/c4d03f09244b3718d0b2e632e55ecda4d94d50b0)
